name: Build Project
on:
  workflow_dispatch: {}
jobs:
  activation:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Build
        id: build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
      - name: Save
        id: save
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build